{
 "title": "Efficiency",
 "tags": [
  "kubernetes-integration",
  "efficiency"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   { "name": "cluster", "label": "cluster", "query": "label_values(up{}, cluster)" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_filesystem_avail_bytes{cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) / sum(kube_node_status_capacity{resource=\"cpu\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Average Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\", cluster=~\"$cluster\"}) / sum(machine_memory_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Average Node \"/\" Storage Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(100 - sum(node_filesystem_avail_bytes{mountpoint=\"/\", cluster=~\"$cluster\", instance=~\"$node\"}  * 100) / sum(node_filesystem_size_bytes{mountpoint=\"/\", cluster=~\"$cluster\", instance=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Average Pods Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_start_time{cluster=~\"$cluster\"}>=${__from:date:seconds})"
    }
   ]
  },
  {
   "title": "Max CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) / sum(kube_node_status_capacity{resource=\"cpu\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Max Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\", cluster=~\"$cluster\"}) / sum(machine_memory_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Max Node \"/\" Storage Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(100 - sum(node_filesystem_avail_bytes{mountpoint=\"/\", cluster=~\"$cluster\", instance=~\"$node\"}  * 100) / sum(node_filesystem_size_bytes{mountpoint=\"/\", cluster=~\"$cluster\", instance=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Average Pods Evicted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_reason{cluster=~\"$cluster\", reason=\"Evicted\"} == 1)"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Memory Utilization Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\", cluster=~\"$cluster\"})",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"})",
     "legendFormat": "Utilization (CPU seconds)"
    }
   ]
  },
  {
   "title": "Persistent Storage Utilization Efficiency",
   "type": "timeseries",
   "description": "Requests refer to the total amount of storage requested by a PV/PVC pair, while utilization shows the amount of actual filesystem space used on a given PV, as reported by kubelet.\n\nIn cases where a PV is backed by a shared storage pool such as NFS, iSCSI, etc, the utilization will show the total utilization of that pool. This can result in dramatically higher utilization than requests.\n\nThe utilization of shared storage pools will also be the total utilization, multiplied by the number of volumes which use that pool.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"}) - sum(kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Pods Started",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~\"$cluster\"} |= \"sourcecomponent=kubelet\" |~ \"kind=Pod\" |~ \"reason=Started\"[$__interval]))",
     "legendFormat": "Pods Started"
    }
   ]
  },
  {
   "title": "Pods Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_status_reason{cluster=~\"$cluster\", reason=\"Evicted\"} == 1)",
     "legendFormat": "Pods Evicted"
    }
   ]
  }
 ]
}