{
 "title": "Meraki Switch Details",
 "description": "Provides an Overview of a specific Meraki Switch",
 "tags": [
  "Meraki",
  "Cisco",
  "Switches"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Switches",
    "label": "Switches",
    "query": {
     "query": "label_values(snmp_scrape_duration_seconds{job_snmp=~\"integrations/snmp\"},snmp_target)"
    }
   },
   {
    "name": "ifName",
    "label": "ifName",
    "query": {
     "query": "label_values(ifType_info{snmp_target=~\"$Switches\"},ifDescr)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview for $Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Switches" },
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{snmp_target=\"$Switches\"}",
     "legendFormat": "__auto",
     "measurement": "snmp.meraki",
     "select": [
      [
       { "params": [ "devStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "devName::tag", "operator": "=~", "value": "/^$Switches$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces for $Switches",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(ifAdminStatus{snmp_target=\"$Switches\"}[$__interval])",
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "ifName::tag" ], "type": "tag" },
      { "params": [ "ifAlias::tag" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp.CISCO",
     "query": "SELECT last(\"ifAdminStatus\") AS \"AdminStatus\", last(\"ifOperStatus\") AS \"OperStatus\", last(\"ifHighSpeed\") AS \"Speed\" FROM \"IF\" WHERE (\"agent_host\" =~ /^$host$/ ) AND time > now() -2m GROUP BY \"ifName\", \"ifAlias\", \"ifOperStatusCause\"",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AdminStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OperStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$Switches$/" }
     ]
    },
    {
     "expr": "last_over_time(ifOperStatus{snmp_target=\"$Switches\"}[$__interval])",
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "ifName::tag" ], "type": "tag" },
      { "params": [ "ifAlias::tag" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp.CISCO",
     "query": "SELECT last(\"ifAdminStatus\") AS \"AdminStatus\", last(\"ifOperStatus\") AS \"OperStatus\", last(\"ifHighSpeed\") AS \"Speed\" FROM \"IF\" WHERE (\"agent_host\" =~ /^$host$/ ) AND time > now() -2m GROUP BY \"ifName\", \"ifAlias\", \"ifOperStatusCause\"",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AdminStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OperStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$Switches$/" }
     ]
    },
    {
     "expr": "last_over_time(ifHighSpeed{snmp_target=\"$Switches\"}[$__interval])",
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "ifName::tag" ], "type": "tag" },
      { "params": [ "ifAlias::tag" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp.CISCO",
     "query": "SELECT last(\"ifAdminStatus\") AS \"AdminStatus\", last(\"ifOperStatus\") AS \"OperStatus\", last(\"ifHighSpeed\") AS \"Speed\" FROM \"IF\" WHERE (\"agent_host\" =~ /^$host$/ ) AND time > now() -2m GROUP BY \"ifName\", \"ifAlias\", \"ifOperStatusCause\"",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AdminStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OperStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$Switches$/" }
     ]
    }
   ]
  },
  { "title": "Interface Statistics $Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Switches" },
  {
   "title": "Network Usage - Traffic Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "ifName",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "Upload",
     "expr": "(\r\n  sum by (snmp_target, ifDescr) (irate(ifHCOutOctets{job_snmp=~\"integrations/snmp\", snmp_target=~\"$Switches\", ifDescr=~\"$ifName\"}[$__interval])) +\r\n  sum by (snmp_target, ifDescr) (irate(ifHCInOctets{job_snmp=~\"integrations/snmp\", snmp_target=~\"$Switches\", ifDescr=~\"$ifName\"}[$__interval]))\r\n) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ifDescr}}",
     "measurement": "snmp.CISCO",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifName::tag", "operator": "=~", "value": "/^$ifName$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Switches$/" }
     ]
    }
   ]
  }
 ]
}