{
 "title": "Windows Active Directory overview",
 "tags": [
  "windows-active-directory-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_ad_binds_total{job=~\"integrations/windows_exporter\", job=~\"$job\"},instance)"
    }
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"integrations/windows.*\"} == 1) > 0) and (absent(absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))) or vector(0) and on() ((count(up{job=~\"integrations/windows.*\"}) > 0) and (absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"integrations/windows.*\"} == 1) > 0) and (absent(absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))) or vector(0) and on() ((count(up{job=~\"integrations/windows.*\"}) > 0) and (absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Replication pending operations",
   "type": "stat",
   "description": "The number of replication operations that are pending in Active Directory.\nThese operations could include a variety of tasks, such as updating directory objects, processing changes made on other domain controllers, or applying new schema updates.\n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_operations{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Directory service threads",
   "type": "stat",
   "description": "The current number of active threads in the directory service.\n",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_ad_directory_service_threads{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Directory service threads"
    }
   ]
  },
  {
   "title": "Windows Active Directory alerts",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 }
  },
  {
   "title": "Replication pending synchronizations",
   "type": "stat",
   "description": "The number of synchronization requests that are pending in Active Directory. Synchronization in AD refers to the process of ensuring that changes (like updates to user accounts, group policies, etc.) are consistently applied across all domain controllers.\n",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_synchronizations{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "LDAP operations",
   "type": "timeseries",
   "description": "The rate of LDAP read, search, and write operations.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_ad_directory_operations_total{origin=~\"ldap\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{ operation }}"
    }
   ]
  },
  {
   "title": "LDAP bind requests",
   "type": "timeseries",
   "description": "The rate at which LDAP bind requests are being made.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_ad_binds_total{bind_method=~\"ldap\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind operations overview",
   "type": "table",
   "description": "Distribution of different types of operations performed on the Active Directory database.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(windows_ad_binds_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Intrasite replication traffic",
   "type": "timeseries",
   "description": "Rate of replication traffic between servers within the same site.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(windows_ad_replication_data_intrasite_bytes_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}} - {{ direction }}"
    }
   ]
  },
  {
   "title": "Intersite replication traffic",
   "type": "timeseries",
   "description": "Rate of replication traffic between servers across different sites.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(windows_ad_replication_data_intersite_bytes_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}} - {{ direction }}"
    }
   ]
  },
  {
   "title": "Inbound replication updates",
   "type": "timeseries",
   "description": "The rate of traffic received from other replication partners.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(windows_ad_replication_inbound_objects_updated_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} objects"
    },
    {
     "expr": "rate(windows_ad_replication_inbound_properties_updated_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} properties"
    }
   ]
  },
  {
   "title": "Database operations overview",
   "type": "table",
   "description": "Distribution of different types of operations performed on the Active Directory database.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(windows_ad_database_operations_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Database operations",
   "type": "timeseries",
   "description": "The rate of database operations.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_ad_database_operations_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{ operation }}"
    }
   ]
  }
 ]
}